### ISSUE TITLE
Logging in kazoo-go library

### ISSUE THREAD

**Issue by tosan88** [Financial-Times/kafka-client-go#11]
The current version of [kazoo library](https://github.com/wvanbergen/kazoo-go) does not allow to specify a custom logger hence some logs from there are continuously showing up, e.g.:
```Oct 04 09:28:08 ip-172-24-76-63.eu-west-1.compute.internal bash[2654]: 2017/10/04 09:28:08 Connected to 172.24.23.250:2181
Oct 04 09:28:08 ip-172-24-76-63.eu-west-1.compute.internal bash[2654]: 2017/10/04 09:28:08 Authenticated: id=98768940725970142, timeout=4000
Oct 04 09:28:08 ip-172-24-76-63.eu-west-1.compute.internal bash[2654]: 2017/10/04 09:28:08 Re-submitting `0` credentials after reconnect
```
The library [has a fix for that](https://github.com/wvanbergen/kazoo-go/pull/26) but it is not yet released, so one solution would be to fork that library with that additional change and use the forked one.

**Comment by khatton-ft** [comment]
Hmm, that kazoo-go project does look a bit dormant.

**Comment by tosan88** [comment]
Update: the fix in the library was released, see https://github.com/wvanbergen/kazoo-go/pull/26

**Comment by david-smith-ft** [comment]
Resolved in https://github.com/Financial-Times/kafka-client-go/pull/13
